version: "3"
services:
      web_app:
           container_name: web
           image: web/app
           restart: always
           build: web
           ports:
             - "3000:3000"
           links:
             - mongo
      mongo:
             container_name: mongo
             image: mongo
             volumes:
               - ./data:/data/db
             ports:
               - '27018:27017'
      api_app:
            container_name: api
            image: api/api
            build: api
      mqtt_app:
            container_name: mqtt
            image: mqtt/mqtt
            build: mqtt